import {
  Link2,
  MessageCircle,
  Wifi,
  AlignLeft,
  MapPin,
  Camera,
  ThumbsUp,
  Mail,
  Phone,
  MessageSquare,
  IdCard,
  UtensilsCrossed,
  Store,
  Percent,
  WholeWord,
  ImageDown,
  Repeat,
  Scale,
  Ruler,
  Combine,
  Split,
  FileOutput,
  FileInput,
  KeyRound,
  ScanLine,
  BadgePercent,
  Receipt,
  Divide,
  Thermometer,
  Coins,
  Pilcrow,
  Eraser,
  FileJson,
  Binary,
  Link,
  Fingerprint,
  Hash,
  Regex,
  Clock,
  CodeXml,
  Timer,
  Watch,
  Dices,
  Users,
  type LucideIcon,
} from "lucide-react";
import type { CategoryId } from "@/lib/tools/categories";

export type ToolStatus = "active" | "beta" | "coming-soon";

export interface Tool {
  id: string;
  slug: string;
  href: string;
  name: string;
  shortName: string;
  description: string;
  category: CategoryId;
  icon: LucideIcon;
  keywords: string[];
  status: ToolStatus;
  relatedTools: string[];
}

/**
 * Central catalog of every tool on Herramio. Adding a new tool anywhere in
 * the product should mean adding one entry here (plus its page) — nothing
 * else should need to hardcode a tool's name, icon, or slug.
 */
export const TOOLS: Tool[] = [
  {
    id: "qr-url",
    slug: "qr-url",
    href: "/qr-url",
    name: "QR para enlaces (URL)",
    shortName: "QR de URL",
    description: "Convierte cualquier enlace o página web en un código QR escaneable.",
    category: "qr",
    icon: Link2,
    keywords: ["url", "enlace", "link", "pagina web", "sitio web"],
    status: "active",
    relatedTools: ["qr-negocio", "qr-menu", "qr-vcard"],
  },
  {
    id: "qr-whatsapp",
    slug: "qr-whatsapp",
    href: "/qr-whatsapp",
    name: "QR de WhatsApp",
    shortName: "QR WhatsApp",
    description: "Crea un QR que abre un chat de WhatsApp con número y mensaje predefinido.",
    category: "qr",
    icon: MessageCircle,
    keywords: ["whatsapp", "chat", "mensaje", "ventas", "atencion al cliente"],
    status: "active",
    relatedTools: ["qr-sms", "qr-telefono", "qr-vcard"],
  },
  {
    id: "qr-wifi",
    slug: "qr-wifi",
    href: "/qr-wifi",
    name: "QR de WiFi",
    shortName: "QR WiFi",
    description: "Comparte tu red WiFi sin decir la contraseña en voz alta.",
    category: "qr",
    icon: Wifi,
    keywords: ["wifi", "red", "contraseña", "internet", "conexion"],
    status: "active",
    relatedTools: ["qr-menu", "qr-negocio", "qr-url"],
  },
  {
    id: "qr-texto",
    slug: "qr-texto",
    href: "/qr-texto",
    name: "QR de texto",
    shortName: "QR de texto",
    description: "Codifica cualquier texto plano, notas o instrucciones en un QR.",
    category: "qr",
    icon: AlignLeft,
    keywords: ["texto", "nota", "instrucciones", "mensaje"],
    status: "active",
    relatedTools: ["qr-url", "qr-email", "qr-vcard"],
  },
  {
    id: "qr-google-maps",
    slug: "qr-google-maps",
    href: "/qr-google-maps",
    name: "QR de Google Maps",
    shortName: "QR Maps",
    description: "Genera un QR que lleva directo a una ubicación o dirección en el mapa.",
    category: "qr",
    icon: MapPin,
    keywords: ["maps", "mapa", "ubicacion", "direccion", "google maps"],
    status: "active",
    relatedTools: ["qr-negocio", "qr-menu", "qr-whatsapp"],
  },
  {
    id: "qr-instagram",
    slug: "qr-instagram",
    href: "/qr-instagram",
    name: "QR de Instagram",
    shortName: "QR Instagram",
    description: "Lleva a tus clientes directo a tu perfil de Instagram con un escaneo.",
    category: "qr",
    icon: Camera,
    keywords: ["instagram", "redes sociales", "perfil", "seguidores"],
    status: "active",
    relatedTools: ["qr-facebook", "qr-negocio", "qr-vcard"],
  },
  {
    id: "qr-facebook",
    slug: "qr-facebook",
    href: "/qr-facebook",
    name: "QR de Facebook",
    shortName: "QR Facebook",
    description: "Comparte tu página o perfil de Facebook mediante un código QR.",
    category: "qr",
    icon: ThumbsUp,
    keywords: ["facebook", "redes sociales", "pagina", "perfil"],
    status: "active",
    relatedTools: ["qr-instagram", "qr-negocio", "qr-whatsapp"],
  },
  {
    id: "qr-email",
    slug: "qr-email",
    href: "/qr-email",
    name: "QR de correo electrónico",
    shortName: "QR Email",
    description: "Genera un QR que abre un correo nuevo con destinatario, asunto y mensaje.",
    category: "qr",
    icon: Mail,
    keywords: ["email", "correo", "mail", "contacto"],
    status: "active",
    relatedTools: ["qr-telefono", "qr-sms", "qr-vcard"],
  },
  {
    id: "qr-telefono",
    slug: "qr-telefono",
    href: "/qr-telefono",
    name: "QR de llamada telefónica",
    shortName: "QR Teléfono",
    description: "Crea un QR que inicia una llamada telefónica al escanearlo.",
    category: "qr",
    icon: Phone,
    keywords: ["telefono", "llamada", "numero", "contacto"],
    status: "active",
    relatedTools: ["qr-whatsapp", "qr-sms", "qr-vcard"],
  },
  {
    id: "qr-sms",
    slug: "qr-sms",
    href: "/qr-sms",
    name: "QR de SMS",
    shortName: "QR SMS",
    description: "Genera un QR que abre la app de mensajes con número y texto predefinidos.",
    category: "qr",
    icon: MessageSquare,
    keywords: ["sms", "mensaje de texto", "telefono"],
    status: "active",
    relatedTools: ["qr-whatsapp", "qr-telefono", "qr-email"],
  },
  {
    id: "qr-vcard",
    slug: "qr-vcard",
    href: "/qr-vcard",
    name: "QR de tarjeta de contacto (vCard)",
    shortName: "QR vCard",
    description: "Comparte tu tarjeta de presentación digital: nombre, teléfono, empresa y más.",
    category: "qr",
    icon: IdCard,
    keywords: ["vcard", "contacto", "tarjeta de presentacion", "negocios"],
    status: "active",
    relatedTools: ["qr-whatsapp", "qr-email", "qr-negocio"],
  },
  {
    id: "qr-menu",
    slug: "qr-menu",
    href: "/qr-menu",
    name: "QR para menú de restaurante",
    shortName: "QR Menú",
    description: "Crea un QR que lleva al menú digital de tu restaurante, bar o cafetería.",
    category: "qr",
    icon: UtensilsCrossed,
    keywords: ["menu", "restaurante", "carta", "bar", "cafeteria"],
    status: "active",
    relatedTools: ["qr-wifi", "qr-negocio", "qr-google-maps"],
  },
  {
    id: "qr-negocio",
    slug: "qr-negocio",
    href: "/qr-negocio",
    name: "QR para negocios",
    shortName: "QR Negocio",
    description: "Un QR todo-en-uno para que tu negocio comparta web, redes y contacto.",
    category: "qr",
    icon: Store,
    keywords: ["negocio", "empresa", "todo en uno", "enlaces"],
    status: "active",
    relatedTools: ["qr-whatsapp", "qr-google-maps", "qr-vcard"],
  },
  {
    id: "calc-porcentaje",
    slug: "calc-porcentaje",
    href: "/calc-porcentaje",
    name: "Calculadora de Porcentaje",
    shortName: "Calc. Porcentaje",
    description: "Calcula porcentajes, aumentos y descuentos al instante.",
    category: "calculadoras",
    icon: Percent,
    keywords: ["porcentaje", "calcular porcentaje", "sacar porcentaje", "descuento", "aumento"],
    status: "active",
    relatedTools: ["calc-imc", "conv-unidades"],
  },
  {
    id: "texto-contador-palabras",
    slug: "texto-contador-palabras",
    href: "/texto-contador-palabras",
    name: "Contador de Palabras y Caracteres",
    shortName: "Contador Palabras",
    description: "Cuenta palabras, caracteres, líneas y tiempo de lectura en tiempo real.",
    category: "texto",
    icon: WholeWord,
    keywords: ["contador de palabras", "contador de caracteres", "contar palabras", "tiempo de lectura"],
    status: "active",
    relatedTools: [],
  },
  {
    id: "imagen-comprimir",
    slug: "imagen-comprimir",
    href: "/imagen-comprimir",
    name: "Comprimir Imagen",
    shortName: "Comprimir imagen",
    description: "Reduce el peso de una imagen JPG, PNG o WebP sin subirla a un servidor.",
    category: "imagenes",
    icon: ImageDown,
    keywords: ["comprimir imagen", "comprimir jpg", "comprimir png", "reducir tamaño imagen"],
    status: "active",
    relatedTools: ["imagen-convertir", "jpg-a-pdf"],
  },
  {
    id: "imagen-convertir",
    slug: "imagen-convertir",
    href: "/imagen-convertir",
    name: "Convertidor de Imágenes",
    shortName: "Convertir imagen",
    description: "Convierte imágenes entre JPG, PNG y WebP directamente en tu navegador.",
    category: "imagenes",
    icon: Repeat,
    keywords: ["convertir imagen", "jpg a png", "png a jpg", "webp a jpg"],
    status: "active",
    relatedTools: ["imagen-comprimir", "jpg-a-pdf"],
  },
  {
    id: "calc-imc",
    slug: "calc-imc",
    href: "/calc-imc",
    name: "Calculadora de IMC",
    shortName: "Calc. IMC",
    description: "Calcula tu índice de masa corporal a partir de tu peso y altura.",
    category: "calculadoras",
    icon: Scale,
    keywords: ["imc", "indice de masa corporal", "calculadora imc", "calcular imc"],
    status: "active",
    relatedTools: ["calc-porcentaje", "conv-unidades"],
  },
  {
    id: "conv-unidades",
    slug: "conv-unidades",
    href: "/conv-unidades",
    name: "Convertidor de Unidades",
    shortName: "Conv. Unidades",
    description: "Convierte longitud, peso, temperatura, área, volumen y tiempo entre unidades.",
    category: "convertidores",
    icon: Ruler,
    keywords: ["convertidor de unidades", "km a millas", "kg a lb", "celsius a fahrenheit"],
    status: "active",
    relatedTools: ["calc-porcentaje", "calc-imc"],
  },
  {
    id: "pdf-unir",
    slug: "pdf-unir",
    href: "/pdf-unir",
    name: "Unir PDF",
    shortName: "Unir PDF",
    description: "Combina varios archivos PDF en uno solo, en el orden que elijas.",
    category: "pdf",
    icon: Combine,
    keywords: ["unir pdf", "combinar pdf", "juntar pdf", "fusionar pdf"],
    status: "active",
    relatedTools: ["pdf-dividir", "jpg-a-pdf"],
  },
  {
    id: "pdf-dividir",
    slug: "pdf-dividir",
    href: "/pdf-dividir",
    name: "Dividir PDF",
    shortName: "Dividir PDF",
    description: "Extrae páginas específicas de un PDF como archivos independientes.",
    category: "pdf",
    icon: Split,
    keywords: ["dividir pdf", "separar pdf", "extraer paginas pdf"],
    status: "active",
    relatedTools: ["pdf-unir", "pdf-a-jpg"],
  },
  {
    id: "jpg-a-pdf",
    slug: "jpg-a-pdf",
    href: "/jpg-a-pdf",
    name: "JPG a PDF",
    shortName: "JPG a PDF",
    description: "Convierte una o varias imágenes JPG o PNG en un solo PDF.",
    category: "pdf",
    icon: FileInput,
    keywords: ["jpg a pdf", "imagen a pdf", "convertir jpg a pdf", "foto a pdf"],
    status: "active",
    relatedTools: ["pdf-a-jpg", "imagen-comprimir"],
  },
  {
    id: "pdf-a-jpg",
    slug: "pdf-a-jpg",
    href: "/pdf-a-jpg",
    name: "PDF a JPG",
    shortName: "PDF a JPG",
    description: "Convierte páginas de un PDF en imágenes JPG descargables.",
    category: "pdf",
    icon: FileOutput,
    keywords: ["pdf a jpg", "convertir pdf a imagen", "pdf a imagen"],
    status: "active",
    relatedTools: ["jpg-a-pdf", "imagen-convertir"],
  },
  {
    id: "texto-generador-contrasenas",
    slug: "texto-generador-contrasenas",
    href: "/texto-generador-contrasenas",
    name: "Generador de Contraseñas Seguras",
    shortName: "Generar contraseña",
    description: "Genera contraseñas aleatorias y seguras con Web Crypto API.",
    category: "texto",
    icon: KeyRound,
    keywords: ["generador de contraseñas", "crear contraseña segura", "password generator"],
    status: "active",
    relatedTools: ["texto-limpiar", "texto-lorem-ipsum"],
  },
  {
    id: "qr-lector",
    slug: "qr-lector",
    href: "/qr-lector",
    name: "Leer Código QR",
    shortName: "Leer QR",
    description: "Sube una imagen con un QR y descubre su contenido al instante.",
    category: "qr",
    icon: ScanLine,
    keywords: ["leer codigo qr", "escanear qr online", "decodificar qr", "qr scanner"],
    status: "active",
    relatedTools: ["qr-url", "qr-vcard", "qr-wifi"],
  },
  {
    id: "calc-descuento",
    slug: "calc-descuento",
    href: "/calc-descuento",
    name: "Calculadora de Descuento",
    shortName: "Calc. Descuento",
    description: "Calcula cuánto ahorras y el precio final con un descuento.",
    category: "calculadoras",
    icon: BadgePercent,
    keywords: ["calculadora de descuento", "calcular descuento", "precio con descuento"],
    status: "active",
    relatedTools: ["calc-porcentaje", "calc-iva"],
  },
  {
    id: "calc-iva",
    slug: "calc-iva",
    href: "/calc-iva",
    name: "Calculadora de IVA",
    shortName: "Calc. IVA",
    description: "Calcula el IVA de un precio, con o sin impuesto incluido.",
    category: "calculadoras",
    icon: Receipt,
    keywords: ["calculadora de iva", "calcular iva", "iva incluido"],
    status: "active",
    relatedTools: ["calc-descuento", "calc-porcentaje"],
  },
  {
    id: "calc-regla-de-tres",
    slug: "calc-regla-de-tres",
    href: "/calc-regla-de-tres",
    name: "Calculadora de Regla de Tres",
    shortName: "Regla de Tres",
    description: "Resuelve reglas de tres directas e inversas.",
    category: "calculadoras",
    icon: Divide,
    keywords: ["regla de tres", "regla de tres simple", "proporciones"],
    status: "active",
    relatedTools: ["calc-porcentaje", "conv-unidades"],
  },
  {
    id: "conv-temperatura",
    slug: "conv-temperatura",
    href: "/conv-temperatura",
    name: "Convertidor de Temperatura",
    shortName: "Conv. Temperatura",
    description: "Convierte Celsius, Fahrenheit y Kelvin al instante.",
    category: "convertidores",
    icon: Thermometer,
    keywords: ["convertidor de temperatura", "celsius a fahrenheit", "fahrenheit a celsius"],
    status: "active",
    relatedTools: ["conv-unidades", "conv-moneda"],
  },
  {
    id: "conv-moneda",
    slug: "conv-moneda",
    href: "/conv-moneda",
    name: "Convertidor de Moneda",
    shortName: "Conv. Moneda",
    description: "Convierte entre más de 30 monedas con tasas actualizadas diariamente.",
    category: "convertidores",
    icon: Coins,
    keywords: ["convertidor de moneda", "tipo de cambio", "conversor de divisas"],
    status: "active",
    relatedTools: ["conv-unidades", "conv-temperatura"],
  },
  {
    id: "texto-lorem-ipsum",
    slug: "texto-lorem-ipsum",
    href: "/texto-lorem-ipsum",
    name: "Generador de Lorem Ipsum",
    shortName: "Lorem Ipsum",
    description: "Genera texto de relleno Lorem Ipsum por palabras, oraciones o párrafos.",
    category: "texto",
    icon: Pilcrow,
    keywords: ["lorem ipsum", "generador de lorem ipsum", "texto de relleno"],
    status: "active",
    relatedTools: ["texto-contador-palabras", "texto-limpiar"],
  },
  {
    id: "texto-limpiar",
    slug: "texto-limpiar",
    href: "/texto-limpiar",
    name: "Limpiador de Texto",
    shortName: "Limpiar Texto",
    description: "Quita espacios duplicados, líneas vacías y normaliza mayúsculas/minúsculas.",
    category: "texto",
    icon: Eraser,
    keywords: ["limpiador de texto", "quitar espacios", "normalizar texto"],
    status: "active",
    relatedTools: ["texto-contador-palabras", "texto-lorem-ipsum"],
  },
  {
    id: "dev-json-formatter",
    slug: "dev-json-formatter",
    href: "/dev-json-formatter",
    name: "Formateador de JSON",
    shortName: "JSON Formatter",
    description: "Formatea, valida y minifica JSON con indentación legible.",
    category: "desarrolladores",
    icon: FileJson,
    keywords: ["json formatter", "formatear json", "validar json", "minificar json", "json beautifier"],
    status: "active",
    relatedTools: ["dev-base64", "dev-url-encoder"],
  },
  {
    id: "dev-base64",
    slug: "dev-base64",
    href: "/dev-base64",
    name: "Codificador/Decodificador Base64",
    shortName: "Base64",
    description: "Codifica y decodifica texto en Base64 directamente en tu navegador.",
    category: "desarrolladores",
    icon: Binary,
    keywords: ["base64", "codificar base64", "decodificar base64", "base64 encode", "base64 decode"],
    status: "active",
    relatedTools: ["dev-json-formatter", "dev-url-encoder"],
  },
  {
    id: "dev-url-encoder",
    slug: "dev-url-encoder",
    href: "/dev-url-encoder",
    name: "Codificador/Decodificador de URL",
    shortName: "URL Encode",
    description: "Codifica y decodifica componentes de URL (percent-encoding).",
    category: "desarrolladores",
    icon: Link,
    keywords: ["url encode", "url decode", "codificar url", "decodificar url", "percent encoding"],
    status: "active",
    relatedTools: ["dev-base64", "dev-html-escape"],
  },
  {
    id: "dev-uuid-generator",
    slug: "dev-uuid-generator",
    href: "/dev-uuid-generator",
    name: "Generador de UUID",
    shortName: "Generar UUID",
    description: "Genera identificadores UUID v4 únicos y aleatorios.",
    category: "desarrolladores",
    icon: Fingerprint,
    keywords: ["generador de uuid", "uuid v4", "guid generator", "generar uuid online"],
    status: "active",
    relatedTools: ["dev-hash-generator", "dev-json-formatter"],
  },
  {
    id: "dev-hash-generator",
    slug: "dev-hash-generator",
    href: "/dev-hash-generator",
    name: "Generador de Hash (SHA-256, SHA-1...)",
    shortName: "Generar Hash",
    description: "Calcula hashes SHA-1, SHA-256, SHA-384 y SHA-512 de cualquier texto.",
    category: "desarrolladores",
    icon: Hash,
    keywords: ["generador de hash", "sha256 online", "calcular hash", "sha1", "sha512"],
    status: "active",
    relatedTools: ["dev-uuid-generator", "dev-base64"],
  },
  {
    id: "dev-regex-tester",
    slug: "dev-regex-tester",
    href: "/dev-regex-tester",
    name: "Probador de Expresiones Regulares",
    shortName: "Regex Tester",
    description: "Prueba expresiones regulares en tiempo real con resaltado de coincidencias.",
    category: "desarrolladores",
    icon: Regex,
    keywords: ["regex tester", "probador de expresiones regulares", "regex online", "regular expression"],
    status: "active",
    relatedTools: ["dev-json-formatter", "dev-html-escape"],
  },
  {
    id: "dev-timestamp-converter",
    slug: "dev-timestamp-converter",
    href: "/dev-timestamp-converter",
    name: "Convertidor de Timestamp Unix",
    shortName: "Timestamp",
    description: "Convierte entre timestamp Unix y fecha legible, en ambas direcciones.",
    category: "desarrolladores",
    icon: Clock,
    keywords: ["timestamp converter", "unix timestamp", "epoch converter", "convertir timestamp"],
    status: "active",
    relatedTools: ["dev-uuid-generator", "dev-json-formatter"],
  },
  {
    id: "dev-html-escape",
    slug: "dev-html-escape",
    href: "/dev-html-escape",
    name: "Escapar/Desescapar HTML",
    shortName: "HTML Escape",
    description: "Convierte caracteres HTML especiales a entidades y viceversa.",
    category: "desarrolladores",
    icon: CodeXml,
    keywords: ["html escape", "html unescape", "entidades html", "escapar html"],
    status: "active",
    relatedTools: ["dev-regex-tester", "dev-url-encoder"],
  },
  {
    id: "productividad-temporizador",
    slug: "productividad-temporizador",
    href: "/productividad-temporizador",
    name: "Temporizador Pomodoro",
    shortName: "Temporizador",
    description: "Temporizador de cuenta regresiva con presets de la técnica Pomodoro.",
    category: "productividad",
    icon: Timer,
    keywords: ["temporizador online", "pomodoro timer", "cuenta regresiva", "temporizador pomodoro"],
    status: "active",
    relatedTools: ["productividad-cronometro", "productividad-sorteador"],
  },
  {
    id: "productividad-cronometro",
    slug: "productividad-cronometro",
    href: "/productividad-cronometro",
    name: "Cronómetro Online",
    shortName: "Cronómetro",
    description: "Cronómetro online preciso, con registro de vueltas.",
    category: "productividad",
    icon: Watch,
    keywords: ["cronometro online", "stopwatch", "cronometro con vueltas", "medir tiempo"],
    status: "active",
    relatedTools: ["productividad-temporizador", "productividad-sorteador"],
  },
  {
    id: "productividad-sorteador",
    slug: "productividad-sorteador",
    href: "/productividad-sorteador",
    name: "Sorteador de Nombres",
    shortName: "Sorteador",
    description: "Elige un ganador al azar entre una lista de nombres.",
    category: "productividad",
    icon: Dices,
    keywords: ["sorteador de nombres", "random name picker", "sorteo online", "elegir ganador al azar"],
    status: "active",
    relatedTools: ["productividad-generador-equipos", "productividad-temporizador"],
  },
  {
    id: "productividad-generador-equipos",
    slug: "productividad-generador-equipos",
    href: "/productividad-generador-equipos",
    name: "Generador de Equipos",
    shortName: "Gen. Equipos",
    description: "Divide una lista de nombres en equipos aleatorios y equilibrados.",
    category: "productividad",
    icon: Users,
    keywords: ["generador de equipos aleatorios", "team randomizer", "dividir en equipos", "sorteo de equipos"],
    status: "active",
    relatedTools: ["productividad-sorteador", "productividad-cronometro"],
  },
];

export function getToolById(id: string): Tool | undefined {
  return TOOLS.find((tool) => tool.id === id);
}

export function getToolsByCategory(category: CategoryId): Tool[] {
  return TOOLS.filter((tool) => tool.category === category);
}

export function getRelatedTools(tool: Tool, limit = 4): Tool[] {
  return tool.relatedTools
    .map((id) => getToolById(id))
    .filter((t): t is Tool => Boolean(t))
    .slice(0, limit);
}
