import {
  Link2,
  MessageCircle,
  Wifi,
  AlignLeft,
  MapPin,
  Camera,
  ThumbsUp,
  Mail,
  Phone,
  MessageSquare,
  IdCard,
  UtensilsCrossed,
  Store,
  Percent,
  WholeWord,
  ImageDown,
  Repeat,
  Scale,
  Ruler,
  Combine,
  Split,
  FileOutput,
  FileInput,
  KeyRound,
  ScanLine,
  BadgePercent,
  Receipt,
  Divide,
  Thermometer,
  Coins,
  Pilcrow,
  Eraser,
  FileJson,
  Binary,
  Link,
  Fingerprint,
  Hash,
  Regex,
  Clock,
  CodeXml,
  Timer,
  Watch,
  Dices,
  Users,
  Palette,
  Cake,
  CalendarDays,
  FileSpreadsheet,
  Slash,
  Wallet,
  Users2,
  ShieldCheck,
  Globe,
  TextSelect,
  Grid3x3,
  Pipette,
  FileMinus,
  RotateCw,
  AtSign,
  ListOrdered,
  Paintbrush,
  Layers,
  Shrink,
  Maximize2,
  Radar,
  TerminalSquare,
  CalendarClock,
  Quote,
  Hourglass,
  TrendingUp,
  Crop,
  FlipHorizontal2,
  Droplets,
  AppWindow,
  ArrowUpDown,
  Banknote,
  Landmark,
  HandCoins,
  AlarmClock,
  Lock,
  Eye,
  Stamp,
  PenLine,
  FileSearch,
  Copyright,
  Scissors,
  SlidersHorizontal,
  FileCode,
  Type,
  CalendarPlus,
  LineChart,
  PiggyBank,
  ExternalLink,
  FilePlus2,
  GitCompareArrows,
  Circle,
  Smile,
  Target,
  Frame,
  Superscript,
  ListTodo,
  FileImage,
  BookImage,
  LayoutGrid,
  SquareRoundCorner,
  HardDrive,
  StickyNote,
  Copy,
  Contrast,
  FileText,
  Smartphone,
  CloudFog,
  Zap,
  Droplet,
  FileCode2,
  Link2Off,
  Search,
  SearchCode,
  type LucideIcon,
} from "lucide-react";
import type { CategoryId } from "@/lib/tools/categories";

export type ToolStatus = "active" | "beta" | "coming-soon";

export interface Tool {
  id: string;
  slug: string;
  href: string;
  name: string;
  shortName: string;
  description: string;
  category: CategoryId;
  icon: LucideIcon;
  keywords: string[];
  status: ToolStatus;
  relatedTools: string[];
  /**
   * "local" (the default when omitted) means every byte the tool touches
   * stays in the browser. Only set "external" when the tool genuinely makes
   * a network request as part of its normal operation (today: only
   * conv-moneda, for live exchange rates) — this field is what the trust
   * badge and category privacy copy read from, so it must stay accurate.
   */
  processing?: "local" | "external";
}

export function isLocalProcessing(tool: Tool): boolean {
  return tool.processing !== "external";
}

/**
 * Central catalog of every tool on Herramio. Adding a new tool anywhere in
 * the product should mean adding one entry here (plus its page) — nothing
 * else should need to hardcode a tool's name, icon, or slug.
 */
export const TOOLS: Tool[] = [
  {
    id: "qr-url",
    slug: "qr-url",
    href: "/qr-url",
    name: "QR para enlaces (URL)",
    shortName: "QR de URL",
    description: "Convierte cualquier enlace o página web en un código QR escaneable.",
    category: "qr",
    icon: Link2,
    keywords: ["url", "enlace", "link", "pagina web", "sitio web"],
    status: "active",
    relatedTools: ["qr-negocio", "qr-menu", "qr-vcard"],
  },
  {
    id: "qr-whatsapp",
    slug: "qr-whatsapp",
    href: "/qr-whatsapp",
    name: "QR de WhatsApp",
    shortName: "QR WhatsApp",
    description: "Crea un QR que abre un chat de WhatsApp con número y mensaje predefinido.",
    category: "qr",
    icon: MessageCircle,
    keywords: ["whatsapp", "chat", "mensaje", "ventas", "atencion al cliente"],
    status: "active",
    relatedTools: ["qr-sms", "qr-telefono", "qr-vcard"],
  },
  {
    id: "qr-wifi",
    slug: "qr-wifi",
    href: "/qr-wifi",
    name: "QR de WiFi",
    shortName: "QR WiFi",
    description: "Comparte tu red WiFi sin decir la contraseña en voz alta.",
    category: "qr",
    icon: Wifi,
    keywords: ["wifi", "red", "contraseña", "internet", "conexion"],
    status: "active",
    relatedTools: ["qr-menu", "qr-negocio", "qr-url"],
  },
  {
    id: "qr-texto",
    slug: "qr-texto",
    href: "/qr-texto",
    name: "QR de texto",
    shortName: "QR de texto",
    description: "Codifica cualquier texto plano, notas o instrucciones en un QR.",
    category: "qr",
    icon: AlignLeft,
    keywords: ["texto", "nota", "instrucciones", "mensaje"],
    status: "active",
    relatedTools: ["qr-url", "qr-email", "qr-vcard"],
  },
  {
    id: "qr-google-maps",
    slug: "qr-google-maps",
    href: "/qr-google-maps",
    name: "QR de Google Maps",
    shortName: "QR Maps",
    description: "Genera un QR que lleva directo a una ubicación o dirección en el mapa.",
    category: "qr",
    icon: MapPin,
    keywords: ["maps", "mapa", "ubicacion", "direccion", "google maps"],
    status: "active",
    relatedTools: ["qr-negocio", "qr-menu", "qr-whatsapp"],
  },
  {
    id: "qr-instagram",
    slug: "qr-instagram",
    href: "/qr-instagram",
    name: "QR de Instagram",
    shortName: "QR Instagram",
    description: "Lleva a tus clientes directo a tu perfil de Instagram con un escaneo.",
    category: "qr",
    icon: Camera,
    keywords: ["instagram", "redes sociales", "perfil", "seguidores"],
    status: "active",
    relatedTools: ["qr-facebook", "qr-negocio", "qr-vcard"],
  },
  {
    id: "qr-facebook",
    slug: "qr-facebook",
    href: "/qr-facebook",
    name: "QR de Facebook",
    shortName: "QR Facebook",
    description: "Comparte tu página o perfil de Facebook mediante un código QR.",
    category: "qr",
    icon: ThumbsUp,
    keywords: ["facebook", "redes sociales", "pagina", "perfil"],
    status: "active",
    relatedTools: ["qr-instagram", "qr-negocio", "qr-whatsapp"],
  },
  {
    id: "qr-email",
    slug: "qr-email",
    href: "/qr-email",
    name: "QR de correo electrónico",
    shortName: "QR Email",
    description: "Genera un QR que abre un correo nuevo con destinatario, asunto y mensaje.",
    category: "qr",
    icon: Mail,
    keywords: ["email", "correo", "mail", "contacto"],
    status: "active",
    relatedTools: ["qr-telefono", "qr-sms", "qr-vcard"],
  },
  {
    id: "qr-telefono",
    slug: "qr-telefono",
    href: "/qr-telefono",
    name: "QR de llamada telefónica",
    shortName: "QR Teléfono",
    description: "Crea un QR que inicia una llamada telefónica al escanearlo.",
    category: "qr",
    icon: Phone,
    keywords: ["telefono", "llamada", "numero", "contacto"],
    status: "active",
    relatedTools: ["qr-whatsapp", "qr-sms", "qr-vcard"],
  },
  {
    id: "qr-sms",
    slug: "qr-sms",
    href: "/qr-sms",
    name: "QR de SMS",
    shortName: "QR SMS",
    description: "Genera un QR que abre la app de mensajes con número y texto predefinidos.",
    category: "qr",
    icon: MessageSquare,
    keywords: ["sms", "mensaje de texto", "telefono"],
    status: "active",
    relatedTools: ["qr-whatsapp", "qr-telefono", "qr-email"],
  },
  {
    id: "qr-vcard",
    slug: "qr-vcard",
    href: "/qr-vcard",
    name: "QR de tarjeta de contacto (vCard)",
    shortName: "QR vCard",
    description: "Comparte tu tarjeta de presentación digital: nombre, teléfono, empresa y más.",
    category: "qr",
    icon: IdCard,
    keywords: ["vcard", "contacto", "tarjeta de presentacion", "negocios"],
    status: "active",
    relatedTools: ["qr-whatsapp", "qr-email", "qr-negocio"],
  },
  {
    id: "qr-menu",
    slug: "qr-menu",
    href: "/qr-menu",
    name: "QR para menú de restaurante",
    shortName: "QR Menú",
    description: "Crea un QR que lleva al menú digital de tu restaurante, bar o cafetería.",
    category: "qr",
    icon: UtensilsCrossed,
    keywords: ["menu", "restaurante", "carta", "bar", "cafeteria"],
    status: "active",
    relatedTools: ["qr-wifi", "qr-negocio", "qr-google-maps"],
  },
  {
    id: "qr-negocio",
    slug: "qr-negocio",
    href: "/qr-negocio",
    name: "QR para negocios",
    shortName: "QR Negocio",
    description: "Un QR todo-en-uno para que tu negocio comparta web, redes y contacto.",
    category: "qr",
    icon: Store,
    keywords: ["negocio", "empresa", "todo en uno", "enlaces"],
    status: "active",
    relatedTools: ["qr-whatsapp", "qr-google-maps", "qr-vcard"],
  },
  {
    id: "calc-porcentaje",
    slug: "calc-porcentaje",
    href: "/calc-porcentaje",
    name: "Calculadora de Porcentaje",
    shortName: "Calc. Porcentaje",
    description: "Calcula porcentajes, aumentos y descuentos al instante.",
    category: "calculadoras",
    icon: Percent,
    keywords: ["porcentaje", "calcular porcentaje", "sacar porcentaje", "descuento", "aumento"],
    status: "active",
    relatedTools: ["calc-imc", "conv-unidades", "finanzas-propina", "finanzas-interes-compuesto"],
  },
  {
    id: "texto-contador-palabras",
    slug: "texto-contador-palabras",
    href: "/texto-contador-palabras",
    name: "Contador de Palabras y Caracteres",
    shortName: "Contador Palabras",
    description: "Cuenta palabras, caracteres, líneas y tiempo de lectura en tiempo real.",
    category: "texto",
    icon: WholeWord,
    keywords: ["contador de palabras", "contador de caracteres", "contar palabras", "tiempo de lectura"],
    status: "active",
    relatedTools: ["texto-citas-apa"],
  },
  {
    id: "imagen-comprimir",
    slug: "imagen-comprimir",
    href: "/imagen-comprimir",
    name: "Comprimir Imagen",
    shortName: "Comprimir imagen",
    description: "Reduce el peso de una imagen JPG, PNG o WebP sin subirla a un servidor.",
    category: "imagenes",
    icon: ImageDown,
    keywords: ["comprimir imagen", "comprimir jpg", "comprimir png", "reducir tamaño imagen"],
    status: "active",
    relatedTools: ["imagen-convertir", "jpg-a-pdf", "imagen-comprimir-a-tamano", "imagen-eliminar-metadata"],
  },
  {
    id: "imagen-convertir",
    slug: "imagen-convertir",
    href: "/imagen-convertir",
    name: "Convertidor de Imágenes",
    shortName: "Convertir imagen",
    description: "Convierte imágenes entre JPG, PNG y WebP directamente en tu navegador.",
    category: "imagenes",
    icon: Repeat,
    keywords: ["convertir imagen", "jpg a png", "png a jpg", "webp a jpg"],
    status: "active",
    relatedTools: ["imagen-comprimir", "jpg-a-pdf", "imagen-paleta-colores", "imagen-redimensionar"],
  },
  {
    id: "calc-imc",
    slug: "calc-imc",
    href: "/calc-imc",
    name: "Calculadora de IMC",
    shortName: "Calc. IMC",
    description: "Calcula tu índice de masa corporal a partir de tu peso y altura.",
    category: "calculadoras",
    icon: Scale,
    keywords: ["imc", "indice de masa corporal", "calculadora imc", "calcular imc"],
    status: "active",
    relatedTools: ["calc-porcentaje", "conv-unidades"],
  },
  {
    id: "conv-unidades",
    slug: "conv-unidades",
    href: "/conv-unidades",
    name: "Convertidor de Unidades",
    shortName: "Conv. Unidades",
    description: "Convierte longitud, peso, temperatura, área, volumen y tiempo entre unidades.",
    category: "convertidores",
    icon: Ruler,
    keywords: ["convertidor de unidades", "km a millas", "kg a lb", "celsius a fahrenheit"],
    status: "active",
    relatedTools: ["calc-porcentaje", "calc-imc"],
  },
  {
    id: "pdf-unir",
    slug: "pdf-unir",
    href: "/pdf-unir",
    name: "Unir PDF",
    shortName: "Unir PDF",
    description: "Combina varios archivos PDF en uno solo, en el orden que elijas.",
    category: "pdf",
    icon: Combine,
    keywords: ["unir pdf", "combinar pdf", "juntar pdf", "fusionar pdf"],
    status: "active",
    relatedTools: ["pdf-dividir", "jpg-a-pdf"],
  },
  {
    id: "pdf-dividir",
    slug: "pdf-dividir",
    href: "/pdf-dividir",
    name: "Dividir PDF",
    shortName: "Dividir PDF",
    description: "Extrae páginas específicas de un PDF como archivos independientes.",
    category: "pdf",
    icon: Split,
    keywords: ["dividir pdf", "separar pdf", "extraer paginas pdf"],
    status: "active",
    relatedTools: ["pdf-unir", "pdf-a-jpg", "pdf-extraer-texto", "pdf-eliminar-paginas", "pdf-marca-agua"],
  },
  {
    id: "jpg-a-pdf",
    slug: "jpg-a-pdf",
    href: "/jpg-a-pdf",
    name: "JPG a PDF",
    shortName: "JPG a PDF",
    description: "Convierte una o varias imágenes JPG o PNG en un solo PDF.",
    category: "pdf",
    icon: FileInput,
    keywords: ["jpg a pdf", "imagen a pdf", "convertir jpg a pdf", "foto a pdf"],
    status: "active",
    relatedTools: ["pdf-a-jpg", "imagen-comprimir"],
  },
  {
    id: "pdf-a-jpg",
    slug: "pdf-a-jpg",
    href: "/pdf-a-jpg",
    name: "PDF a JPG",
    shortName: "PDF a JPG",
    description: "Convierte páginas de un PDF en imágenes JPG descargables.",
    category: "pdf",
    icon: FileOutput,
    keywords: ["pdf a jpg", "convertir pdf a imagen", "pdf a imagen"],
    status: "active",
    relatedTools: ["jpg-a-pdf", "pdf-a-png", "pdf-extraer-texto"],
  },
  {
    id: "texto-generador-contrasenas",
    slug: "texto-generador-contrasenas",
    href: "/texto-generador-contrasenas",
    name: "Generador de Contraseñas Seguras",
    shortName: "Generar contraseña",
    description: "Genera contraseñas aleatorias y seguras con Web Crypto API.",
    category: "texto",
    icon: KeyRound,
    keywords: ["generador de contraseñas", "crear contraseña segura", "password generator"],
    status: "active",
    relatedTools: ["texto-limpiar", "texto-lorem-ipsum", "texto-verificar-contrasena"],
  },
  {
    id: "qr-lector",
    slug: "qr-lector",
    href: "/qr-lector",
    name: "Leer Código QR",
    shortName: "Leer QR",
    description: "Sube una imagen con un QR y descubre su contenido al instante.",
    category: "qr",
    icon: ScanLine,
    keywords: ["leer codigo qr", "escanear qr online", "decodificar qr", "qr scanner"],
    status: "active",
    relatedTools: ["qr-url", "qr-vcard", "qr-wifi"],
  },
  {
    id: "calc-descuento",
    slug: "calc-descuento",
    href: "/calc-descuento",
    name: "Calculadora de Descuento",
    shortName: "Calc. Descuento",
    description: "Calcula cuánto ahorras y el precio final con un descuento.",
    category: "calculadoras",
    icon: BadgePercent,
    keywords: ["calculadora de descuento", "calcular descuento", "precio con descuento"],
    status: "active",
    relatedTools: ["calc-porcentaje", "calc-iva"],
  },
  {
    id: "calc-iva",
    slug: "calc-iva",
    href: "/calc-iva",
    name: "Calculadora de IVA",
    shortName: "Calc. IVA",
    description: "Calcula el IVA de un precio, con o sin impuesto incluido.",
    category: "calculadoras",
    icon: Receipt,
    keywords: ["calculadora de iva", "calcular iva", "iva incluido"],
    status: "active",
    relatedTools: ["calc-descuento", "calc-porcentaje"],
  },
  {
    id: "calc-regla-de-tres",
    slug: "calc-regla-de-tres",
    href: "/calc-regla-de-tres",
    name: "Calculadora de Regla de Tres",
    shortName: "Regla de Tres",
    description: "Resuelve reglas de tres directas e inversas.",
    category: "calculadoras",
    icon: Divide,
    keywords: ["regla de tres", "regla de tres simple", "proporciones"],
    status: "active",
    relatedTools: ["calc-porcentaje", "conv-unidades"],
  },
  {
    id: "conv-temperatura",
    slug: "conv-temperatura",
    href: "/conv-temperatura",
    name: "Convertidor de Temperatura",
    shortName: "Conv. Temperatura",
    description: "Convierte Celsius, Fahrenheit y Kelvin al instante.",
    category: "convertidores",
    icon: Thermometer,
    keywords: ["convertidor de temperatura", "celsius a fahrenheit", "fahrenheit a celsius"],
    status: "active",
    relatedTools: ["conv-unidades", "conv-moneda", "conv-zona-horaria"],
  },
  {
    id: "conv-moneda",
    slug: "conv-moneda",
    href: "/conv-moneda",
    name: "Convertidor de Moneda",
    shortName: "Conv. Moneda",
    description: "Convierte entre más de 30 monedas con tasas actualizadas diariamente.",
    category: "convertidores",
    icon: Coins,
    keywords: ["convertidor de moneda", "tipo de cambio", "conversor de divisas"],
    status: "active",
    relatedTools: ["conv-unidades", "conv-temperatura"],
    processing: "external",
  },
  {
    id: "texto-lorem-ipsum",
    slug: "texto-lorem-ipsum",
    href: "/texto-lorem-ipsum",
    name: "Generador de Lorem Ipsum",
    shortName: "Lorem Ipsum",
    description: "Genera texto de relleno Lorem Ipsum por palabras, oraciones o párrafos.",
    category: "texto",
    icon: Pilcrow,
    keywords: ["lorem ipsum", "generador de lorem ipsum", "texto de relleno"],
    status: "active",
    relatedTools: ["texto-contador-palabras", "texto-limpiar"],
  },
  {
    id: "texto-limpiar",
    slug: "texto-limpiar",
    href: "/texto-limpiar",
    name: "Limpiador de Texto",
    shortName: "Limpiar Texto",
    description: "Quita espacios duplicados, líneas vacías y normaliza mayúsculas/minúsculas.",
    category: "texto",
    icon: Eraser,
    keywords: ["limpiador de texto", "quitar espacios", "normalizar texto"],
    status: "active",
    relatedTools: ["texto-contador-palabras", "texto-lorem-ipsum", "texto-slug", "texto-extraer-emails"],
  },
  {
    id: "dev-json-formatter",
    slug: "dev-json-formatter",
    href: "/dev-json-formatter",
    name: "Formateador de JSON",
    shortName: "JSON Formatter",
    description: "Formatea, valida y minifica JSON con indentación legible.",
    category: "desarrolladores",
    icon: FileJson,
    keywords: ["json formatter", "formatear json", "validar json", "minificar json", "json beautifier"],
    status: "active",
    relatedTools: ["dev-json-a-typescript", "dev-csv-json", "dev-jwt-decoder"],
  },
  {
    id: "dev-base64",
    slug: "dev-base64",
    href: "/dev-base64",
    name: "Codificador/Decodificador Base64",
    shortName: "Base64",
    description: "Codifica y decodifica texto en Base64 directamente en tu navegador.",
    category: "desarrolladores",
    icon: Binary,
    keywords: ["base64", "codificar base64", "decodificar base64", "base64 encode", "base64 decode"],
    status: "active",
    relatedTools: ["dev-json-formatter", "dev-url-encoder"],
  },
  {
    id: "dev-url-encoder",
    slug: "dev-url-encoder",
    href: "/dev-url-encoder",
    name: "Codificador/Decodificador de URL",
    shortName: "URL Encode",
    description: "Codifica y decodifica componentes de URL (percent-encoding).",
    category: "desarrolladores",
    icon: Link,
    keywords: ["url encode", "url decode", "codificar url", "decodificar url", "percent encoding"],
    status: "active",
    relatedTools: ["dev-url-parser", "dev-html-escape"],
  },
  {
    id: "dev-uuid-generator",
    slug: "dev-uuid-generator",
    href: "/dev-uuid-generator",
    name: "Generador de UUID",
    shortName: "Generar UUID",
    description: "Genera identificadores UUID v4 únicos y aleatorios.",
    category: "desarrolladores",
    icon: Fingerprint,
    keywords: ["generador de uuid", "uuid v4", "guid generator", "generar uuid online"],
    status: "active",
    relatedTools: ["dev-hash-generator", "dev-json-formatter"],
  },
  {
    id: "dev-hash-generator",
    slug: "dev-hash-generator",
    href: "/dev-hash-generator",
    name: "Generador de Hash (SHA-256, SHA-1...)",
    shortName: "Generar Hash",
    description: "Calcula hashes SHA-1, SHA-256, SHA-384 y SHA-512 de cualquier texto.",
    category: "desarrolladores",
    icon: Hash,
    keywords: ["generador de hash", "sha256 online", "calcular hash", "sha1", "sha512"],
    status: "active",
    relatedTools: ["dev-uuid-generator", "dev-base64"],
  },
  {
    id: "dev-regex-tester",
    slug: "dev-regex-tester",
    href: "/dev-regex-tester",
    name: "Probador de Expresiones Regulares",
    shortName: "Regex Tester",
    description: "Prueba expresiones regulares en tiempo real con resaltado de coincidencias.",
    category: "desarrolladores",
    icon: Regex,
    keywords: ["regex tester", "probador de expresiones regulares", "regex online", "regular expression"],
    status: "active",
    relatedTools: ["dev-regex-explicador", "dev-html-escape"],
  },
  {
    id: "dev-timestamp-converter",
    slug: "dev-timestamp-converter",
    href: "/dev-timestamp-converter",
    name: "Convertidor de Timestamp Unix",
    shortName: "Timestamp",
    description: "Convierte entre timestamp Unix y fecha legible, en ambas direcciones.",
    category: "desarrolladores",
    icon: Clock,
    keywords: ["timestamp converter", "unix timestamp", "epoch converter", "convertir timestamp"],
    status: "active",
    relatedTools: ["dev-uuid-generator", "dev-json-formatter", "dev-cron"],
  },
  {
    id: "dev-html-escape",
    slug: "dev-html-escape",
    href: "/dev-html-escape",
    name: "Escapar/Desescapar HTML",
    shortName: "HTML Escape",
    description: "Convierte caracteres HTML especiales a entidades y viceversa.",
    category: "desarrolladores",
    icon: CodeXml,
    keywords: ["html escape", "html unescape", "entidades html", "escapar html"],
    status: "active",
    relatedTools: ["dev-regex-tester", "dev-url-encoder"],
  },
  {
    id: "productividad-temporizador",
    slug: "productividad-temporizador",
    href: "/productividad-temporizador",
    name: "Temporizador Pomodoro",
    shortName: "Temporizador",
    description: "Temporizador de cuenta regresiva con presets de la técnica Pomodoro.",
    category: "productividad",
    icon: Timer,
    keywords: ["temporizador online", "pomodoro timer", "cuenta regresiva", "temporizador pomodoro"],
    status: "active",
    relatedTools: ["productividad-cronometro", "productividad-sorteador"],
  },
  {
    id: "productividad-cronometro",
    slug: "productividad-cronometro",
    href: "/productividad-cronometro",
    name: "Cronómetro Online",
    shortName: "Cronómetro",
    description: "Cronómetro online preciso, con registro de vueltas.",
    category: "productividad",
    icon: Watch,
    keywords: ["cronometro online", "stopwatch", "cronometro con vueltas", "medir tiempo"],
    status: "active",
    relatedTools: ["productividad-temporizador", "productividad-sorteador", "productividad-horas-decimal"],
  },
  {
    id: "productividad-sorteador",
    slug: "productividad-sorteador",
    href: "/productividad-sorteador",
    name: "Sorteador de Nombres",
    shortName: "Sorteador",
    description: "Elige un ganador al azar entre una lista de nombres.",
    category: "productividad",
    icon: Dices,
    keywords: ["sorteador de nombres", "random name picker", "sorteo online", "elegir ganador al azar"],
    status: "active",
    relatedTools: ["productividad-generador-equipos", "productividad-temporizador"],
  },
  {
    id: "productividad-generador-equipos",
    slug: "productividad-generador-equipos",
    href: "/productividad-generador-equipos",
    name: "Generador de Equipos",
    shortName: "Gen. Equipos",
    description: "Divide una lista de nombres en equipos aleatorios y equilibrados.",
    category: "productividad",
    icon: Users,
    keywords: ["generador de equipos aleatorios", "team randomizer", "dividir en equipos", "sorteo de equipos"],
    status: "active",
    relatedTools: ["productividad-sorteador", "productividad-cronometro"],
  },
  {
    id: "dev-color-picker",
    slug: "dev-color-picker",
    href: "/dev-color-picker",
    name: "Convertidor de Color (HEX, RGB, HSL)",
    shortName: "Convertidor Color",
    description: "Convierte colores entre HEX, RGB y HSL al instante, con selector visual.",
    category: "desarrolladores",
    icon: Palette,
    keywords: ["convertidor de color", "hex a rgb", "rgb a hsl", "color picker online", "hex to rgb"],
    status: "active",
    relatedTools: ["dev-csv-json", "dev-json-formatter", "dev-gradiente-css"],
  },
  {
    id: "dev-csv-json",
    slug: "dev-csv-json",
    href: "/dev-csv-json",
    name: "Convertidor CSV a JSON",
    shortName: "CSV ↔ JSON",
    description: "Convierte de CSV a JSON y de JSON a CSV, en ambas direcciones.",
    category: "desarrolladores",
    icon: FileSpreadsheet,
    keywords: ["csv a json", "json a csv", "convertidor csv json", "csv to json online"],
    status: "active",
    relatedTools: ["dev-json-formatter", "dev-color-picker"],
  },
  {
    id: "calc-edad",
    slug: "calc-edad",
    href: "/calc-edad",
    name: "Calculadora de Edad",
    shortName: "Calc. Edad",
    description: "Calcula tu edad exacta en años, meses y días a partir de tu fecha de nacimiento.",
    category: "calculadoras",
    icon: Cake,
    keywords: ["calculadora de edad", "cuantos años tengo", "calcular edad exacta"],
    status: "active",
    relatedTools: ["calc-fecha", "calc-porcentaje"],
  },
  {
    id: "calc-fecha",
    slug: "calc-fecha",
    href: "/calc-fecha",
    name: "Calculadora de Diferencia entre Fechas",
    shortName: "Dif. de Fechas",
    description: "Calcula cuántos días, semanas, meses o años hay entre dos fechas.",
    category: "calculadoras",
    icon: CalendarDays,
    keywords: ["dias entre fechas", "calculadora de fechas", "diferencia entre fechas", "calcular dias"],
    status: "active",
    relatedTools: ["calc-edad", "calc-porcentaje", "productividad-fecha-futura"],
  },
  {
    id: "texto-slug",
    slug: "texto-slug",
    href: "/texto-slug",
    name: "Generador de Slugs",
    shortName: "Generador Slug",
    description: "Convierte cualquier texto en un slug limpio y listo para usar en URLs.",
    category: "texto",
    icon: Slash,
    keywords: ["generador de slug", "slugify", "texto a url", "convertir texto a slug", "url amigable"],
    status: "active",
    relatedTools: ["texto-limpiar", "texto-contador-palabras"],
  },
  {
    id: "finanzas-propina",
    slug: "finanzas-propina",
    href: "/finanzas-propina",
    name: "Calculadora de Propina",
    shortName: "Calc. Propina",
    description: "Calcula la propina y el total a pagar, dividido entre las personas que quieras.",
    category: "calculadoras",
    icon: Wallet,
    keywords: ["calculadora de propina", "calcular propina", "tip calculator", "cuanto de propina"],
    status: "active",
    relatedTools: ["finanzas-dividir-cuenta", "calc-porcentaje"],
  },
  {
    id: "finanzas-dividir-cuenta",
    slug: "finanzas-dividir-cuenta",
    href: "/finanzas-dividir-cuenta",
    name: "Dividir Cuenta entre Amigos",
    shortName: "Dividir Cuenta",
    description: "Reparte una cuenta con propina incluida entre varias personas al instante.",
    category: "calculadoras",
    icon: Users2,
    keywords: ["dividir cuenta", "repartir gastos", "dividir gastos entre amigos", "split bill"],
    status: "active",
    relatedTools: ["finanzas-propina", "calc-porcentaje", "finanzas-dividir-gastos-grupo"],
  },
  {
    id: "dev-jwt-decoder",
    slug: "dev-jwt-decoder",
    href: "/dev-jwt-decoder",
    name: "Decodificador de JWT",
    shortName: "JWT Decoder",
    description: "Decodifica el header y payload de un token JWT directamente en tu navegador.",
    category: "desarrolladores",
    icon: ShieldCheck,
    keywords: ["jwt decoder", "decodificar jwt", "jwt online", "leer token jwt", "json web token"],
    status: "active",
    relatedTools: ["dev-json-formatter", "dev-base64"],
  },
  {
    id: "conv-zona-horaria",
    slug: "conv-zona-horaria",
    href: "/conv-zona-horaria",
    name: "Convertidor de Zona Horaria",
    shortName: "Conv. Zona Horaria",
    description: "Convierte una hora entre dos zonas horarias, con horario de verano incluido.",
    category: "convertidores",
    icon: Globe,
    keywords: ["convertidor de zona horaria", "cambiar hora entre zonas", "time zone converter"],
    status: "active",
    relatedTools: ["conv-temperatura", "conv-unidades"],
  },
  {
    id: "pdf-extraer-texto",
    slug: "pdf-extraer-texto",
    href: "/pdf-extraer-texto",
    name: "Extraer Texto de PDF",
    shortName: "Extraer Texto PDF",
    description: "Extrae todo el texto de un PDF y cópialo o descárgalo como archivo .txt.",
    category: "pdf",
    icon: TextSelect,
    keywords: ["extraer texto de pdf", "pdf a texto", "copiar texto de pdf", "pdf to text"],
    status: "active",
    relatedTools: ["pdf-a-jpg", "pdf-comparar-texto", "pdf-comprimir"],
  },
  {
    id: "pdf-comprimir",
    slug: "pdf-comprimir",
    href: "/pdf-comprimir",
    name: "Comprimir PDF",
    shortName: "Comprimir PDF",
    description: "Reduce el peso de un PDF recomprimiendo sus páginas como imágenes, ideal para escaneados.",
    category: "pdf",
    icon: Shrink,
    keywords: ["comprimir pdf", "reducir peso de pdf", "pdf mas liviano", "comprimir pdf online gratis"],
    status: "active",
    relatedTools: ["pdf-extraer-texto", "pdf-dividir"],
  },
  {
    id: "imagen-redimensionar",
    slug: "imagen-redimensionar",
    href: "/imagen-redimensionar",
    name: "Redimensionar Imagen",
    shortName: "Redimensionar Imagen",
    description: "Cambia el tamaño de una imagen a medida o con tamaños listos para Instagram, TikTok y más.",
    category: "imagenes",
    icon: Maximize2,
    keywords: ["redimensionar imagen", "cambiar tamaño de imagen", "imagen para instagram", "resize image online"],
    status: "active",
    relatedTools: ["imagen-comprimir", "imagen-convertir"],
  },
  {
    id: "imagen-eliminar-metadata",
    slug: "imagen-eliminar-metadata",
    href: "/imagen-eliminar-metadata",
    name: "Eliminar Metadata de Imagen",
    shortName: "Eliminar Metadata",
    description: "Descubre qué datos ocultos (cámara, fecha, ubicación GPS) trae tu foto y elimínalos antes de compartirla.",
    category: "imagenes",
    icon: Radar,
    keywords: ["eliminar metadata de imagen", "quitar exif", "borrar ubicacion de una foto", "eliminar datos gps foto"],
    status: "active",
    relatedTools: ["imagen-comprimir", "imagen-pixelar", "pdf-eliminar-metadata"],
  },
  {
    id: "imagen-ascii",
    slug: "imagen-ascii",
    href: "/imagen-ascii",
    name: "Convertir Imagen a ASCII Art",
    shortName: "Imagen a ASCII",
    description: "Convierte cualquier foto en arte ASCII de texto, listo para copiar o descargar.",
    category: "imagenes",
    icon: TerminalSquare,
    keywords: ["imagen a ascii", "ascii art generator", "convertir foto a texto", "arte ascii online"],
    status: "active",
    relatedTools: ["imagen-paleta-colores", "imagen-pixelar"],
  },
  {
    id: "dev-cron",
    slug: "dev-cron",
    href: "/dev-cron",
    name: "Traductor de Expresiones Cron",
    shortName: "Traductor Cron",
    description: "Traduce una expresión cron a lenguaje natural y calcula sus próximas ejecuciones.",
    category: "desarrolladores",
    icon: CalendarClock,
    keywords: ["cron expression translator", "que significa esta expresion cron", "crontab generator", "cron a texto"],
    status: "active",
    relatedTools: ["dev-timestamp-converter", "dev-regex-tester"],
  },
  {
    id: "texto-citas-apa",
    slug: "texto-citas-apa",
    href: "/texto-citas-apa",
    name: "Generador de Citas APA",
    shortName: "Citas APA",
    description: "Genera citas en formato APA 7 para libros, sitios web y artículos de revista.",
    category: "texto",
    icon: Quote,
    keywords: ["generador de citas apa", "formato apa 7", "como citar en apa", "referencias apa online"],
    status: "active",
    relatedTools: ["texto-contador-palabras", "texto-limpiar"],
  },
  {
    id: "productividad-horas-decimal",
    slug: "productividad-horas-decimal",
    href: "/productividad-horas-decimal",
    name: "Convertidor de Horas a Decimal",
    shortName: "Horas a Decimal",
    description: "Convierte horas y minutos a formato decimal y suma varias jornadas, ideal para nóminas.",
    category: "productividad",
    icon: Hourglass,
    keywords: ["convertir horas a decimal", "calculadora de horas trabajadas", "horas y minutos a decimal", "hoja de horas"],
    status: "active",
    relatedTools: ["productividad-cronometro", "calc-porcentaje"],
  },
  {
    id: "finanzas-interes-compuesto",
    slug: "finanzas-interes-compuesto",
    href: "/finanzas-interes-compuesto",
    name: "Calculadora de Interés Compuesto",
    shortName: "Interés Compuesto",
    description: "Calcula cuánto crece tu dinero con interés compuesto y aportes mensuales, año a año.",
    category: "calculadoras",
    icon: TrendingUp,
    keywords: ["calculadora de interes compuesto", "interes compuesto online", "calcular crecimiento de inversion"],
    status: "active",
    relatedTools: ["finanzas-propina", "calc-porcentaje"],
  },
  {
    id: "imagen-pixelar",
    slug: "imagen-pixelar",
    href: "/imagen-pixelar",
    name: "Pixelar Imagen",
    shortName: "Pixelar Imagen",
    description: "Pixela una cara, un documento o cualquier zona sensible de una imagen antes de compartirla.",
    category: "imagenes",
    icon: Grid3x3,
    keywords: ["pixelar imagen", "pixelar cara", "ocultar información imagen", "censurar imagen", "difuminar cara"],
    status: "active",
    relatedTools: ["imagen-comprimir", "imagen-convertir"],
  },
  {
    id: "imagen-paleta-colores",
    slug: "imagen-paleta-colores",
    href: "/imagen-paleta-colores",
    name: "Extractor de Paleta de Colores",
    shortName: "Paleta de Colores",
    description: "Sube una imagen y obtén los colores dominantes en HEX, listos para copiar.",
    category: "imagenes",
    icon: Pipette,
    keywords: ["extractor de colores", "paleta de colores de imagen", "colores dominantes", "sacar colores de una foto"],
    status: "active",
    relatedTools: ["imagen-color-picker", "imagen-comprimir"],
  },
  {
    id: "pdf-eliminar-paginas",
    slug: "pdf-eliminar-paginas",
    href: "/pdf-eliminar-paginas",
    name: "Eliminar Páginas de PDF",
    shortName: "Eliminar Páginas",
    description: "Quita páginas específicas de un PDF y descarga el resultado al instante.",
    category: "pdf",
    icon: FileMinus,
    keywords: ["eliminar paginas pdf", "quitar paginas de un pdf", "borrar hoja de pdf"],
    status: "active",
    relatedTools: ["pdf-dividir", "pdf-rotar"],
  },
  {
    id: "pdf-rotar",
    slug: "pdf-rotar",
    href: "/pdf-rotar",
    name: "Rotar PDF",
    shortName: "Rotar PDF",
    description: "Rota todas las páginas de un PDF o solo las que elijas, en 90°, 180° o 270°.",
    category: "pdf",
    icon: RotateCw,
    keywords: ["rotar pdf", "girar pdf", "rotar paginas pdf", "voltear pdf"],
    status: "active",
    relatedTools: ["pdf-eliminar-paginas", "pdf-dividir"],
  },
  {
    id: "texto-extraer-emails",
    slug: "texto-extraer-emails",
    href: "/texto-extraer-emails",
    name: "Extractor de Correos Electrónicos",
    shortName: "Extractor de Emails",
    description: "Extrae todas las direcciones de correo de un texto y cópialas de un clic.",
    category: "texto",
    icon: AtSign,
    keywords: ["extractor de emails", "extraer correos de un texto", "buscar emails en texto", "sacar correos"],
    status: "active",
    relatedTools: ["texto-ordenar-lineas", "texto-extraer-urls"],
  },
  {
    id: "texto-ordenar-lineas",
    slug: "texto-ordenar-lineas",
    href: "/texto-ordenar-lineas",
    name: "Ordenar y Eliminar Líneas Duplicadas",
    shortName: "Ordenar Líneas",
    description: "Ordena una lista alfabéticamente, quita duplicados y líneas vacías al instante.",
    category: "texto",
    icon: ListOrdered,
    keywords: ["ordenar lineas", "eliminar lineas duplicadas", "quitar duplicados de una lista", "ordenar lista alfabeticamente"],
    status: "active",
    relatedTools: ["texto-extraer-emails", "texto-limpiar"],
  },
  {
    id: "dev-gradiente-css",
    slug: "dev-gradiente-css",
    href: "/dev-gradiente-css",
    name: "Generador de Gradientes CSS",
    shortName: "Gradientes CSS",
    description: "Crea gradientes CSS personalizados con vista previa en vivo y copia el código.",
    category: "desarrolladores",
    icon: Paintbrush,
    keywords: ["generador de gradientes css", "css gradient generator", "crear gradiente css", "linear-gradient"],
    status: "active",
    relatedTools: ["dev-sombra-css", "dev-color-picker"],
  },
  {
    id: "dev-sombra-css",
    slug: "dev-sombra-css",
    href: "/dev-sombra-css",
    name: "Generador de Sombras CSS",
    shortName: "Sombras CSS",
    description: "Diseña sombras (box-shadow) con capas múltiples y copia el código CSS al instante.",
    category: "desarrolladores",
    icon: Layers,
    keywords: ["generador de sombras css", "box shadow generator", "crear sombra css", "box-shadow"],
    status: "active",
    relatedTools: ["dev-gradiente-css", "dev-color-picker"],
  },
  {
    id: "imagen-recortar",
    slug: "imagen-recortar",
    href: "/imagen-recortar",
    name: "Recortar Imagen",
    shortName: "Recortar Imagen",
    description: "Recorta una imagen a medida o con proporciones listas para Instagram y TikTok.",
    category: "imagenes",
    icon: Crop,
    keywords: ["recortar imagen", "cortar imagen online", "crop image online", "recortar foto"],
    status: "active",
    relatedTools: ["imagen-circulo", "imagen-rotar-voltear"],
  },
  {
    id: "imagen-rotar-voltear",
    slug: "imagen-rotar-voltear",
    href: "/imagen-rotar-voltear",
    name: "Rotar y Voltear Imagen",
    shortName: "Rotar/Voltear",
    description: "Gira una imagen 90°/180°/270° o voltéala en horizontal y vertical.",
    category: "imagenes",
    icon: FlipHorizontal2,
    keywords: ["rotar imagen", "voltear imagen", "girar foto online", "flip image online"],
    status: "active",
    relatedTools: ["imagen-espejo-simetria", "imagen-comprimir"],
  },
  {
    id: "imagen-desenfocar",
    slug: "imagen-desenfocar",
    href: "/imagen-desenfocar",
    name: "Desenfocar Zona de Imagen",
    shortName: "Desenfocar Imagen",
    description: "Difumina una cara o un dato sensible de una imagen de forma suave, antes de compartirla.",
    category: "imagenes",
    icon: Droplets,
    keywords: ["desenfocar imagen", "difuminar foto", "blur imagen online", "difuminar cara"],
    status: "active",
    relatedTools: ["imagen-pixelar", "imagen-eliminar-metadata"],
  },
  {
    id: "imagen-favicon",
    slug: "imagen-favicon",
    href: "/imagen-favicon",
    name: "Generador de Favicon",
    shortName: "Generador Favicon",
    description: "Convierte un logo o imagen en los tamaños de favicon que necesita tu sitio web.",
    category: "imagenes",
    icon: AppWindow,
    keywords: ["generador de favicon", "crear favicon online", "favicon generator", "icono para sitio web"],
    status: "active",
    relatedTools: ["imagen-redimensionar", "imagen-convertir"],
  },
  {
    id: "pdf-reordenar-paginas",
    slug: "pdf-reordenar-paginas",
    href: "/pdf-reordenar-paginas",
    name: "Reordenar y Duplicar Páginas de PDF",
    shortName: "Reordenar Páginas",
    description: "Cambia el orden de las páginas de un PDF o duplica alguna, sin herramientas externas.",
    category: "pdf",
    icon: ArrowUpDown,
    keywords: ["reordenar paginas pdf", "cambiar orden de paginas pdf", "duplicar pagina pdf"],
    status: "active",
    relatedTools: ["pdf-eliminar-paginas", "pdf-dividir"],
  },
  {
    id: "pdf-numerar-paginas",
    slug: "pdf-numerar-paginas",
    href: "/pdf-numerar-paginas",
    name: "Numerar Páginas de PDF",
    shortName: "Numerar Páginas",
    description: "Añade números de página a un PDF, con la posición y el número inicial que elijas.",
    category: "pdf",
    icon: Hash,
    keywords: ["numerar paginas pdf", "agregar numero de pagina a pdf", "poner numeros en pdf"],
    status: "active",
    relatedTools: ["pdf-duplicar-pagina", "pdf-dividir"],
  },
  {
    id: "finanzas-salario",
    slug: "finanzas-salario",
    href: "/finanzas-salario",
    name: "Convertidor de Salario",
    shortName: "Conv. Salario",
    description: "Convierte tu salario entre por hora, diario, mensual y anual, con tu horario real de trabajo.",
    category: "calculadoras",
    icon: Banknote,
    keywords: ["convertidor de salario", "salario por hora a mensual", "calculadora de sueldo", "sueldo anual a mensual"],
    status: "active",
    relatedTools: ["productividad-horas-decimal", "finanzas-interes-compuesto"],
  },
  {
    id: "finanzas-prestamo",
    slug: "finanzas-prestamo",
    href: "/finanzas-prestamo",
    name: "Calculadora de Préstamo y Cuotas",
    shortName: "Calc. Préstamo",
    description: "Calcula la cuota mensual de un préstamo y su tabla de amortización completa.",
    category: "calculadoras",
    icon: Landmark,
    keywords: ["calculadora de prestamo", "calcular cuota de prestamo", "tabla de amortizacion", "calculadora de credito"],
    status: "active",
    relatedTools: ["finanzas-interes-compuesto", "finanzas-salario"],
  },
  {
    id: "finanzas-dividir-gastos-grupo",
    slug: "finanzas-dividir-gastos-grupo",
    href: "/finanzas-dividir-gastos-grupo",
    name: "Dividir Gastos de Grupo",
    shortName: "Gastos de Grupo",
    description: "Reparte gastos entre varias personas con aportes distintos y calcula quién le debe a quién.",
    category: "calculadoras",
    icon: HandCoins,
    keywords: ["dividir gastos de viaje", "calculadora quien debe a quien", "repartir gastos entre amigos", "splitwise gratis"],
    status: "active",
    relatedTools: ["finanzas-dividir-cuenta", "finanzas-propina"],
  },
  {
    id: "productividad-cuenta-regresiva",
    slug: "productividad-cuenta-regresiva",
    href: "/productividad-cuenta-regresiva",
    name: "Cuenta Regresiva para una Fecha",
    shortName: "Cuenta Regresiva",
    description: "Crea una cuenta regresiva en vivo hasta cualquier fecha y hora que elijas.",
    category: "productividad",
    icon: AlarmClock,
    keywords: ["cuenta regresiva online", "contador para una fecha", "cuanto falta para", "countdown timer online"],
    status: "active",
    relatedTools: ["productividad-lista-tareas", "productividad-temporizador"],
  },
  {
    id: "texto-verificar-contrasena",
    slug: "texto-verificar-contrasena",
    href: "/texto-verificar-contrasena",
    name: "Verificar Fuerza de Contraseña",
    shortName: "Verificar Contraseña",
    description: "Comprueba qué tan segura es una contraseña y qué le falta para ser más fuerte.",
    category: "texto",
    icon: Lock,
    keywords: ["verificar seguridad de contraseña", "fuerza de contraseña", "password strength checker", "que tan segura es mi contraseña"],
    status: "active",
    relatedTools: ["texto-generador-contrasenas", "privacidad-info-navegador"],
  },
  {
    id: "privacidad-info-navegador",
    slug: "privacidad-info-navegador",
    href: "/privacidad-info-navegador",
    name: "Qué Sabe tu Navegador de Ti",
    shortName: "Info del Navegador",
    description: "Descubre qué información expone tu navegador a cualquier sitio que visitas.",
    category: "desarrolladores",
    icon: Eye,
    keywords: ["que informacion expone mi navegador", "user agent parser", "informacion de mi navegador", "huella digital del navegador"],
    status: "active",
    relatedTools: ["texto-verificar-contrasena", "imagen-eliminar-metadata"],
  },
  {
    id: "pdf-marca-agua",
    slug: "pdf-marca-agua",
    href: "/pdf-marca-agua",
    name: "Añadir Marca de Agua a PDF",
    shortName: "Marca de Agua PDF",
    description: "Estampa un texto semitransparente en diagonal sobre todas las páginas de un PDF.",
    category: "pdf",
    icon: Stamp,
    keywords: ["marca de agua pdf", "watermark pdf online", "poner marca de agua a un pdf", "estampar pdf"],
    status: "active",
    relatedTools: ["pdf-portada", "pdf-eliminar-metadata"],
  },
  {
    id: "pdf-firmar",
    slug: "pdf-firmar",
    href: "/pdf-firmar",
    name: "Firmar PDF",
    shortName: "Firmar PDF",
    description: "Dibuja tu firma y colócala en cualquier página de un PDF, sin instalar nada.",
    category: "pdf",
    icon: PenLine,
    keywords: ["firmar pdf online", "poner firma en pdf", "agregar firma a documento", "sign pdf online"],
    status: "active",
    relatedTools: ["pdf-marca-agua", "pdf-dividir"],
  },
  {
    id: "pdf-eliminar-metadata",
    slug: "pdf-eliminar-metadata",
    href: "/pdf-eliminar-metadata",
    name: "Eliminar Metadata de PDF",
    shortName: "Eliminar Metadata PDF",
    description: "Descubre qué metadata oculta (autor, título, programa) tiene tu PDF y elimínala.",
    category: "pdf",
    icon: FileSearch,
    keywords: ["eliminar metadata de pdf", "quitar autor de un pdf", "metadata oculta pdf", "limpiar propiedades de pdf"],
    status: "active",
    relatedTools: ["imagen-eliminar-metadata", "pdf-marca-agua"],
  },
  {
    id: "imagen-marca-agua",
    slug: "imagen-marca-agua",
    href: "/imagen-marca-agua",
    name: "Añadir Marca de Agua a Imagen",
    shortName: "Marca de Agua Imagen",
    description: "Repite un texto semitransparente sobre una imagen para protegerla antes de compartirla.",
    category: "imagenes",
    icon: Copyright,
    keywords: ["marca de agua para imagenes", "watermark imagen online", "poner marca de agua a una foto"],
    status: "active",
    relatedTools: ["imagen-comprimir", "imagen-eliminar-metadata"],
  },
  {
    id: "imagen-eliminar-fondo-color",
    slug: "imagen-eliminar-fondo-color",
    href: "/imagen-eliminar-fondo-color",
    name: "Eliminar Fondo de Color Sólido",
    shortName: "Eliminar Fondo",
    description: "Quita un fondo blanco o de un solo color de una imagen y descárgala en PNG transparente.",
    category: "imagenes",
    icon: Scissors,
    keywords: ["eliminar fondo blanco imagen", "quitar fondo de una foto", "fondo transparente online", "chroma key online"],
    status: "active",
    relatedTools: ["imagen-cambiar-fondo", "imagen-sombra"],
  },
  {
    id: "imagen-filtros",
    slug: "imagen-filtros",
    href: "/imagen-filtros",
    name: "Filtros para Imágenes",
    shortName: "Filtros de Imagen",
    description: "Aplica blanco y negro, sepia, brillo, contraste y más filtros a una imagen en tiempo real.",
    category: "imagenes",
    icon: SlidersHorizontal,
    keywords: ["filtros para fotos online", "poner foto en blanco y negro", "editar brillo y contraste online", "filtro sepia online"],
    status: "active",
    relatedTools: ["imagen-efecto-glitch", "imagen-duotono"],
  },
  {
    id: "conv-markdown-html",
    slug: "conv-markdown-html",
    href: "/conv-markdown-html",
    name: "Convertidor de Markdown a HTML",
    shortName: "Markdown a HTML",
    description: "Convierte Markdown a HTML con vista previa en vivo, listo para copiar.",
    category: "convertidores",
    icon: FileCode,
    keywords: ["markdown a html", "convertidor de markdown", "markdown to html online", "vista previa de markdown"],
    status: "active",
    relatedTools: ["conv-html-a-texto", "texto-limpiar"],
  },
  {
    id: "conv-numero-a-letras",
    slug: "conv-numero-a-letras",
    href: "/conv-numero-a-letras",
    name: "Convertidor de Número a Letras",
    shortName: "Número a Letras",
    description: "Convierte cualquier número en su escritura completa en letras, en español.",
    category: "convertidores",
    icon: Type,
    keywords: ["numero a letras", "convertir numero a texto", "escribir numero en letras", "numero en palabras español"],
    status: "active",
    relatedTools: ["conv-romanos", "finanzas-salario"],
  },
  {
    id: "productividad-fecha-futura",
    slug: "productividad-fecha-futura",
    href: "/productividad-fecha-futura",
    name: "Calcular Fecha Futura o Pasada",
    shortName: "Fecha Futura",
    description: "Suma o resta días, semanas, meses o años a una fecha y descubre el resultado al instante.",
    category: "productividad",
    icon: CalendarPlus,
    keywords: ["que fecha sera dentro de", "sumar dias a una fecha", "calcular fecha futura", "restar dias a una fecha"],
    status: "active",
    relatedTools: ["calc-fecha", "productividad-cuenta-regresiva"],
  },
  {
    id: "finanzas-inflacion",
    slug: "finanzas-inflacion",
    href: "/finanzas-inflacion",
    name: "Calculadora de Inflación",
    shortName: "Calc. Inflación",
    description: "Calcula cuánto valdría hoy una cantidad de dinero dentro de X años, según la inflación.",
    category: "calculadoras",
    icon: LineChart,
    keywords: ["calculadora de inflacion", "efecto de la inflacion en el dinero", "cuanto valdra mi dinero en el futuro"],
    status: "active",
    relatedTools: ["finanzas-interes-compuesto", "finanzas-salario"],
  },
  {
    id: "finanzas-ahorro-objetivo",
    slug: "finanzas-ahorro-objetivo",
    href: "/finanzas-ahorro-objetivo",
    name: "Calculadora de Ahorro Objetivo",
    shortName: "Ahorro Objetivo",
    description: "Calcula cuánto debes ahorrar cada mes para alcanzar una meta de ahorro.",
    category: "calculadoras",
    icon: PiggyBank,
    keywords: ["cuanto ahorrar al mes", "calculadora de meta de ahorro", "cuanto ahorrar para comprar algo"],
    status: "active",
    relatedTools: ["finanzas-interes-compuesto", "finanzas-inflacion"],
  },
  {
    id: "texto-extraer-urls",
    slug: "texto-extraer-urls",
    href: "/texto-extraer-urls",
    name: "Extractor de URLs",
    shortName: "Extractor de URLs",
    description: "Extrae todos los enlaces de un texto y cópialos de un clic.",
    category: "texto",
    icon: ExternalLink,
    keywords: ["extractor de urls", "extraer enlaces de un texto", "sacar links de un texto", "extract urls from text"],
    status: "active",
    relatedTools: ["texto-extraer-hashtags", "texto-extraer-emails"],
  },
  {
    id: "pdf-recortar",
    slug: "pdf-recortar",
    href: "/pdf-recortar",
    name: "Recortar Márgenes de PDF",
    shortName: "Recortar PDF",
    description: "Recorta los márgenes blancos de un PDF ajustando el área visible de cada página.",
    category: "pdf",
    icon: Crop,
    keywords: ["recortar pdf", "quitar margenes de un pdf", "cortar bordes de un pdf", "crop pdf online"],
    status: "active",
    relatedTools: ["pdf-marca-agua", "pdf-comprimir"],
  },
  {
    id: "pdf-insertar-pagina-blanca",
    slug: "pdf-insertar-pagina-blanca",
    href: "/pdf-insertar-pagina-blanca",
    name: "Insertar Página en Blanco en PDF",
    shortName: "Insertar Página Blanca",
    description: "Añade una página en blanco en cualquier posición de un PDF.",
    category: "pdf",
    icon: FilePlus2,
    keywords: ["insertar pagina en blanco pdf", "agregar pagina vacia a un pdf", "add blank page pdf"],
    status: "active",
    relatedTools: ["pdf-numerar-paginas", "pdf-reordenar-paginas"],
  },
  {
    id: "pdf-comparar-texto",
    slug: "pdf-comparar-texto",
    href: "/pdf-comparar-texto",
    name: "Comparar Texto de Dos PDF",
    shortName: "Comparar PDF",
    description: "Compara el texto de dos PDF y resalta lo que se agregó o se quitó entre versiones.",
    category: "pdf",
    icon: GitCompareArrows,
    keywords: ["comparar pdf", "diferencias entre dos pdf", "comparar dos versiones de un documento", "pdf diff online"],
    status: "active",
    relatedTools: ["pdf-extraer-texto", "pdf-marca-agua"],
  },
  {
    id: "imagen-circulo",
    slug: "imagen-circulo",
    href: "/imagen-circulo",
    name: "Recortar Imagen en Círculo",
    shortName: "Recorte Circular",
    description: "Recorta una imagen en forma de círculo y descárgala en PNG con fondo transparente.",
    category: "imagenes",
    icon: Circle,
    keywords: ["recortar foto en circulo", "hacer foto de perfil circular", "avatar circular online", "circle crop image"],
    status: "active",
    relatedTools: ["imagen-esquinas-redondeadas", "imagen-comprimir"],
  },
  {
    id: "imagen-meme",
    slug: "imagen-meme",
    href: "/imagen-meme",
    name: "Generador de Memes",
    shortName: "Generador de Memes",
    description: "Agrega texto superior e inferior estilo meme a cualquier imagen y descárgala.",
    category: "imagenes",
    icon: Smile,
    keywords: ["generador de memes", "crear meme online", "poner texto a una imagen estilo meme", "meme generator"],
    status: "active",
    relatedTools: ["imagen-marca-agua", "imagen-filtros"],
  },
  {
    id: "imagen-comprimir-a-tamano",
    slug: "imagen-comprimir-a-tamano",
    href: "/imagen-comprimir-a-tamano",
    name: "Comprimir Imagen a un Tamaño Exacto",
    shortName: "Comprimir a Tamaño",
    description: "Comprime una imagen hasta alcanzar un tamaño en KB específico, como 100 KB o 200 KB.",
    category: "imagenes",
    icon: Target,
    keywords: ["comprimir imagen a 100kb", "reducir imagen a un tamaño especifico", "comprimir foto a un peso exacto"],
    status: "active",
    relatedTools: ["imagen-comprimir", "imagen-convertir"],
  },
  {
    id: "imagen-marco",
    slug: "imagen-marco",
    href: "/imagen-marco",
    name: "Añadir Marco a una Imagen",
    shortName: "Marco de Imagen",
    description: "Agrega un marco de color y ancho ajustable alrededor de una imagen.",
    category: "imagenes",
    icon: Frame,
    keywords: ["marco para fotos online", "añadir borde a una imagen", "poner marco a una foto", "image border online"],
    status: "active",
    relatedTools: ["imagen-collage", "imagen-comprimir"],
  },
  {
    id: "conv-base-numerica",
    slug: "conv-base-numerica",
    href: "/conv-base-numerica",
    name: "Convertidor de Base Numérica",
    shortName: "Base Numérica",
    description: "Convierte entre binario, octal, decimal y hexadecimal al instante.",
    category: "convertidores",
    icon: Binary,
    keywords: ["convertidor binario decimal", "convertir hexadecimal a decimal", "binario a decimal online", "number base converter"],
    status: "active",
    relatedTools: ["dev-hash-generator", "conv-romanos"],
  },
  {
    id: "conv-romanos",
    slug: "conv-romanos",
    href: "/conv-romanos",
    name: "Convertidor de Números Romanos",
    shortName: "Números Romanos",
    description: "Convierte números arábigos a números romanos y viceversa.",
    category: "convertidores",
    icon: Superscript,
    keywords: ["numeros romanos", "convertidor de numeros romanos", "como se escribe en numeros romanos", "roman numeral converter"],
    status: "active",
    relatedTools: ["conv-numero-a-letras", "conv-base-numerica"],
  },
  {
    id: "productividad-lista-tareas",
    slug: "productividad-lista-tareas",
    href: "/productividad-lista-tareas",
    name: "Lista de Tareas Online",
    shortName: "Lista de Tareas",
    description: "Una lista de tareas simple que guarda tus pendientes en este navegador.",
    category: "productividad",
    icon: ListTodo,
    keywords: ["lista de tareas online", "to do list online", "gestor de tareas simple", "checklist online"],
    status: "active",
    relatedTools: ["productividad-cuenta-regresiva", "productividad-fecha-futura"],
  },
  {
    id: "pdf-a-png",
    slug: "pdf-a-png",
    href: "/pdf-a-png",
    name: "Convertir PDF a PNG",
    shortName: "PDF a PNG",
    description: "Convierte cada página de un PDF en una imagen PNG sin pérdida de calidad.",
    category: "pdf",
    icon: FileImage,
    keywords: ["pdf a png", "convertir pdf a imagen png", "pdf to png online", "exportar pdf como png"],
    status: "active",
    relatedTools: ["pdf-a-jpg", "pdf-comprimir"],
  },
  {
    id: "pdf-portada",
    slug: "pdf-portada",
    href: "/pdf-portada",
    name: "Añadir Portada a un PDF",
    shortName: "Portada de PDF",
    description: "Añade una imagen como primera página (portada) de un PDF.",
    category: "pdf",
    icon: BookImage,
    keywords: ["añadir portada a un pdf", "agregar imagen como primera pagina pdf", "add cover page pdf"],
    status: "active",
    relatedTools: ["pdf-marca-agua", "pdf-insertar-pagina-blanca"],
  },
  {
    id: "imagen-color-picker",
    slug: "imagen-color-picker",
    href: "/imagen-color-picker",
    name: "Sacar Color de una Imagen",
    shortName: "Color de Imagen",
    description: "Haz clic en cualquier punto de una imagen para obtener su color exacto en HEX y RGB.",
    category: "imagenes",
    icon: Pipette,
    keywords: ["sacar color de una imagen", "eyedropper online", "obtener color hex de una foto", "color picker de imagen"],
    status: "active",
    relatedTools: ["imagen-paleta-colores", "dev-color-picker"],
  },
  {
    id: "imagen-collage",
    slug: "imagen-collage",
    href: "/imagen-collage",
    name: "Crear Collage de Fotos",
    shortName: "Collage de Fotos",
    description: "Combina de 2 a 4 imágenes en un solo collage en cuadrícula, listo para descargar.",
    category: "imagenes",
    icon: LayoutGrid,
    keywords: ["crear collage online", "unir fotos en una imagen", "collage de fotos gratis", "photo collage maker"],
    status: "active",
    relatedTools: ["imagen-marco", "imagen-comprimir"],
  },
  {
    id: "imagen-esquinas-redondeadas",
    slug: "imagen-esquinas-redondeadas",
    href: "/imagen-esquinas-redondeadas",
    name: "Redondear Esquinas de una Imagen",
    shortName: "Esquinas Redondeadas",
    description: "Redondea las esquinas de una imagen con un radio ajustable y descárgala en PNG transparente.",
    category: "imagenes",
    icon: SquareRoundCorner,
    keywords: ["redondear esquinas de una imagen", "bordes redondeados a una foto online", "rounded corners image"],
    status: "active",
    relatedTools: ["imagen-circulo", "imagen-marco"],
  },
  {
    id: "conv-datos",
    slug: "conv-datos",
    href: "/conv-datos",
    name: "Convertidor de Tamaño de Datos",
    shortName: "Tamaño de Datos",
    description: "Convierte entre bytes, KB, MB, GB y TB, en base binaria o decimal.",
    category: "convertidores",
    icon: HardDrive,
    keywords: ["convertir mb a gb", "convertidor de bytes", "kb a mb online", "data size converter"],
    status: "active",
    relatedTools: ["imagen-comprimir-a-tamano", "conv-base-numerica"],
  },
  {
    id: "texto-comparar",
    slug: "texto-comparar",
    href: "/texto-comparar",
    name: "Comparar Dos Textos",
    shortName: "Comparar Textos",
    description: "Compara dos textos y resalta lo que se agregó o se quitó entre ellos.",
    category: "texto",
    icon: GitCompareArrows,
    keywords: ["comparar dos textos", "diff de texto online", "encontrar diferencias entre textos", "text compare online"],
    status: "active",
    relatedTools: ["pdf-comparar-texto", "texto-limpiar"],
  },
  {
    id: "productividad-notas-rapidas",
    slug: "productividad-notas-rapidas",
    href: "/productividad-notas-rapidas",
    name: "Notas Rápidas Online",
    shortName: "Notas Rápidas",
    description: "Un bloc de notas simple que guarda tu texto en este navegador automáticamente.",
    category: "productividad",
    icon: StickyNote,
    keywords: ["bloc de notas online", "notas rapidas online", "notepad online", "apuntes rapidos sin cuenta"],
    status: "active",
    relatedTools: ["productividad-lista-tareas", "texto-comparar"],
  },
  {
    id: "pdf-duplicar-pagina",
    slug: "pdf-duplicar-pagina",
    href: "/pdf-duplicar-pagina",
    name: "Duplicar Página de un PDF",
    shortName: "Duplicar Página",
    description: "Duplica una página específica de un PDF, insertando la copia justo después.",
    category: "pdf",
    icon: Copy,
    keywords: ["duplicar pagina pdf", "copiar pagina de un pdf", "repetir pagina en un pdf", "duplicate page pdf"],
    status: "active",
    relatedTools: ["pdf-insertar-pagina-blanca", "pdf-numerar-paginas"],
  },
  {
    id: "pdf-escala-grises",
    slug: "pdf-escala-grises",
    href: "/pdf-escala-grises",
    name: "Convertir PDF a Escala de Grises",
    shortName: "PDF a Escala de Grises",
    description: "Convierte todas las páginas de un PDF a blanco y negro, ideal para imprimir.",
    category: "pdf",
    icon: Contrast,
    keywords: ["pdf a escala de grises", "convertir pdf a blanco y negro", "pdf grayscale online", "quitar color de un pdf"],
    status: "active",
    relatedTools: ["pdf-comprimir", "pdf-a-png"],
  },
  {
    id: "pdf-eliminar-paginas-blancas",
    slug: "pdf-eliminar-paginas-blancas",
    href: "/pdf-eliminar-paginas-blancas",
    name: "Eliminar Páginas en Blanco de un PDF",
    shortName: "Quitar Páginas en Blanco",
    description: "Detecta y elimina automáticamente las páginas en blanco de un PDF escaneado.",
    category: "pdf",
    icon: Eraser,
    keywords: ["eliminar paginas en blanco pdf", "quitar hojas vacias de un pdf", "detectar paginas vacias pdf", "remove blank pages pdf"],
    status: "active",
    relatedTools: ["pdf-eliminar-paginas", "pdf-comprimir"],
  },
  {
    id: "pdf-combinar-con-imagenes",
    slug: "pdf-combinar-con-imagenes",
    href: "/pdf-combinar-con-imagenes",
    name: "Combinar PDF con Imágenes",
    shortName: "Combinar PDF e Imágenes",
    description: "Combina varios PDF e imágenes, en el orden que quieras, en un solo documento PDF.",
    category: "pdf",
    icon: Combine,
    keywords: ["combinar pdf con imagenes", "unir pdf y fotos en un documento", "merge pdf and images online"],
    status: "active",
    relatedTools: ["pdf-unir", "jpg-a-pdf"],
  },
  {
    id: "pdf-crear-desde-texto",
    slug: "pdf-crear-desde-texto",
    href: "/pdf-crear-desde-texto",
    name: "Crear PDF desde Texto",
    shortName: "Texto a PDF",
    description: "Convierte cualquier texto en un documento PDF paginado, listo para descargar.",
    category: "pdf",
    icon: FileText,
    keywords: ["crear pdf desde texto", "convertir texto a pdf online", "texto a pdf gratis", "text to pdf"],
    status: "active",
    relatedTools: ["pdf-marca-agua", "pdf-numerar-paginas"],
  },
  {
    id: "imagen-recortar-redes-sociales",
    slug: "imagen-recortar-redes-sociales",
    href: "/imagen-recortar-redes-sociales",
    name: "Recortar Imagen para Redes Sociales",
    shortName: "Recorte para Redes",
    description: "Recorta una imagen a los formatos exactos de Instagram, TikTok, YouTube, LinkedIn y más.",
    category: "imagenes",
    icon: Smartphone,
    keywords: ["recortar imagen para instagram", "tamaño de imagen para tiktok", "medidas para miniatura de youtube", "recorte para redes sociales"],
    status: "active",
    relatedTools: ["imagen-recortar", "imagen-comprimir"],
  },
  {
    id: "imagen-sombra",
    slug: "imagen-sombra",
    href: "/imagen-sombra",
    name: "Añadir Sombra a una Imagen",
    shortName: "Sombra de Imagen",
    description: "Agrega una sombra suave y ajustable alrededor de una imagen con fondo transparente.",
    category: "imagenes",
    icon: CloudFog,
    keywords: ["añadir sombra a una imagen", "drop shadow online", "sombra para foto de producto", "image shadow generator"],
    status: "active",
    relatedTools: ["imagen-eliminar-fondo-color", "imagen-marco"],
  },
  {
    id: "imagen-cambiar-fondo",
    slug: "imagen-cambiar-fondo",
    href: "/imagen-cambiar-fondo",
    name: "Cambiar Fondo de Color de una Imagen",
    shortName: "Cambiar Fondo",
    description: "Reemplaza un fondo de color sólido por otro color a tu elección.",
    category: "imagenes",
    icon: Pipette,
    keywords: ["cambiar fondo de una foto", "reemplazar fondo blanco por color", "cambiar color de fondo online"],
    status: "active",
    relatedTools: ["imagen-eliminar-fondo-color", "imagen-comprimir"],
  },
  {
    id: "imagen-efecto-glitch",
    slug: "imagen-efecto-glitch",
    href: "/imagen-efecto-glitch",
    name: "Efecto Glitch para Imágenes",
    shortName: "Efecto Glitch",
    description: "Aplica un efecto glitch con separación de canales de color a cualquier imagen.",
    category: "imagenes",
    icon: Zap,
    keywords: ["efecto glitch online", "glitch a una foto", "efecto rgb split", "distorsionar imagen online"],
    status: "active",
    relatedTools: ["imagen-duotono", "imagen-filtros"],
  },
  {
    id: "imagen-duotono",
    slug: "imagen-duotono",
    href: "/imagen-duotono",
    name: "Efecto Duotono para Imágenes",
    shortName: "Efecto Duotono",
    description: "Convierte una imagen en un efecto duotono de dos colores, con presets listos para usar.",
    category: "imagenes",
    icon: Droplet,
    keywords: ["efecto duotono online", "duotone image effect", "efecto de dos colores en una foto", "gradient map online"],
    status: "active",
    relatedTools: ["imagen-efecto-glitch", "imagen-filtros"],
  },
  {
    id: "imagen-espejo-simetria",
    slug: "imagen-espejo-simetria",
    href: "/imagen-espejo-simetria",
    name: "Efecto Espejo y Simetría",
    shortName: "Espejo y Simetría",
    description: "Duplica una mitad de una imagen sobre la otra en espejo, creando un efecto de simetría perfecta.",
    category: "imagenes",
    icon: FlipHorizontal2,
    keywords: ["efecto espejo foto", "simetria facial online", "mirror effect image", "simetria perfecta cara"],
    status: "active",
    relatedTools: ["imagen-rotar-voltear", "imagen-filtros"],
  },
  {
    id: "dev-json-a-typescript",
    slug: "dev-json-a-typescript",
    href: "/dev-json-a-typescript",
    name: "Convertidor de JSON a TypeScript",
    shortName: "JSON a TypeScript",
    description: "Genera interfaces de TypeScript a partir de un objeto JSON, con tipos anidados incluidos.",
    category: "desarrolladores",
    icon: FileCode2,
    keywords: ["json a typescript", "generar interface desde json", "json to typescript online", "convertir json en tipos"],
    status: "active",
    relatedTools: ["dev-json-formatter", "dev-csv-json"],
  },
  {
    id: "dev-url-parser",
    slug: "dev-url-parser",
    href: "/dev-url-parser",
    name: "Analizador de URL",
    shortName: "Analizador de URL",
    description: "Descompone una URL en protocolo, host, ruta y parámetros de consulta.",
    category: "desarrolladores",
    icon: Link2Off,
    keywords: ["analizador de url", "parsear url online", "extraer parametros de una url", "url parser online"],
    status: "active",
    relatedTools: ["dev-url-encoder", "texto-extraer-urls"],
  },
  {
    id: "dev-http-status",
    slug: "dev-http-status",
    href: "/dev-http-status",
    name: "Referencia de Códigos HTTP",
    shortName: "Códigos HTTP",
    description: "Busca y consulta el significado de los códigos de estado HTTP más comunes.",
    category: "desarrolladores",
    icon: Search,
    keywords: ["codigos de estado http", "que significa error 404", "lista de codigos http", "http status codes"],
    status: "active",
    relatedTools: ["dev-url-parser", "dev-json-formatter"],
  },
  {
    id: "dev-regex-explicador",
    slug: "dev-regex-explicador",
    href: "/dev-regex-explicador",
    name: "Explicador de Expresiones Regulares",
    shortName: "Explicador de Regex",
    description: "Explica parte por parte qué hace una expresión regular, en español sencillo.",
    category: "desarrolladores",
    icon: SearchCode,
    keywords: ["explicar expresion regular", "que hace este regex", "regex explainer online", "entender una regex"],
    status: "active",
    relatedTools: ["dev-regex-tester", "dev-url-parser"],
  },
  {
    id: "texto-extraer-hashtags",
    slug: "texto-extraer-hashtags",
    href: "/texto-extraer-hashtags",
    name: "Extractor de Hashtags",
    shortName: "Extractor de Hashtags",
    description: "Extrae todos los #hashtags de un texto y cópialos de un clic.",
    category: "texto",
    icon: Hash,
    keywords: ["extraer hashtags de un texto", "sacar hashtags de una publicacion", "extract hashtags from text"],
    status: "active",
    relatedTools: ["texto-extraer-urls", "texto-extraer-emails"],
  },
  {
    id: "conv-html-a-texto",
    slug: "conv-html-a-texto",
    href: "/conv-html-a-texto",
    name: "Convertidor de HTML a Texto",
    shortName: "HTML a Texto",
    description: "Elimina las etiquetas HTML de un contenido y deja solo el texto plano.",
    category: "convertidores",
    icon: FileText,
    keywords: ["html a texto", "quitar etiquetas html", "convertir html a texto plano", "html to text online"],
    status: "active",
    relatedTools: ["conv-markdown-html", "texto-limpiar"],
  },
];

export function getToolById(id: string): Tool | undefined {
  return TOOLS.find((tool) => tool.id === id);
}

export function getToolsByCategory(category: CategoryId): Tool[] {
  return TOOLS.filter((tool) => tool.category === category);
}

export function getRelatedTools(tool: Tool, limit = 4): Tool[] {
  return tool.relatedTools
    .map((id) => getToolById(id))
    .filter((t): t is Tool => Boolean(t))
    .slice(0, limit);
}
